.PHONY: default fonts

default:
	TYPST_FONT_PATHS=./fonts typst watch cv.typ "Samir Rashid Resume.pdf"

compile:
	TYPST_FONT_PATHS=./fonts typst compile cv.typ "Samir Rashid Resume.pdf"

fonts:
	TYPST_FONT_PATHS=./fonts typst fonts

